In [187]:
import pandas as pd
import numpy as np

In [188]:
job_posting_data = pd.read_csv("./output/wanted_crawling_output_1_1_500.csv")
position_data = pd.read_csv("../data/link_job.csv", encoding='cp949')

In [196]:
job_posting_data

,id,title,company,location,tags,qualifications,preferred,benefits,skills,workplace
0,82530,FLO DBA,드림어스컴퍼니,"['서울', '한국']","['인원급성장', '301~1,000명', '설립10년이상', '대출지원', '건강...","['• DBA 경력 5년 이상이신 분', '• 대용량 DBMS 운영 경험하신 분',...","['• 클라우드 환경에서 ISMS 심사 경험이 있는 분', '• 모델링 설계 지원,...","['Work l 드림어스는 개인의 자율성을 존중합니다', '• 선택적 근로시간제에 ...","['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaS...",서초구 강남대로 311 드림플러스 강남 15층
1,147597,전기차충전기 임베디드 소프트웨어 개발,타디스테크놀로지,"['서울', '한국']","['인원급성장', '50명이하', '설립4~9년', '성과급', '스톡옵션', '자...","['• 하드웨어를 제어하는데 관심이 많으신 분', '• 기술 표준 R&D에 관심이 ...","['• 컴퓨터/시스템공학, 전기/전자공학', '• 개발 경험이 있으신 분']","['• 최신형 장비 지원', '- 최신형 맥북이나 델 노트북, 24인치 모니터 지급...","['Git', 'Github', 'Linux', 'React', 'SQL', 'AW...","성동구 성수일로 10 (성수동1가, 서울숲ITCT지식산업센터)"
2,163951,[빗썸] Front End (5년 이상),빗썸코리아,"['서울', '한국']","['연봉상위1%', '인원급성장', '301~1,000명', '설립4~9년', '음...",['• 컴퓨터 공학 또는 관련 분야의 학사 학위 (또는 동등한 실무 경험)를 보유하...,"['• 가상자산 거래소 또는 금융 관련 프로젝트 경험을 보유하신 분', '• 자산 ...","['[업무에 몰입할 수 있는 환경을 조성합니다.]', '', '• 비포괄임금제 | ...",['Agile'],"서울시 강남구 테헤란로 124, 삼원타워 15~17F"
3,122553,소프트웨어 엔지니어 (최적화 엔진 개발),위밋모빌리티,"['서울', '한국']","['유연근무', '스타트업', '간식', '건강검진', '교육비', '재택근무', ...","['• 다양한 프로그래밍 언어를 자유롭게 활용 가능하신 분', '• 자료구조 및 알...","['• 새로운 도메인에 대한 학습 능력 및 문제해결 역량을 갖추신 분', '• 응용...","['기업문화 - 자율성 속에 질서를 위한 규칙이 있어요!', '', '1. 수평적인...","['Git', 'Azure', 'MongoDB', 'Pytorch', 'Scikit...",서울특별시 마포구 백범로31길 21 서울창업허브 본관 615호
4,157234,SW 개발자 (신입),오투오,"['서울', '한국']","['퇴사율5%이하', '50명이하', '설립4~9년', '간식', '인공지능', '...","['- HTML, CSS등 W3C 웹 표준 이해와 UI개발 경험', '- JavaS...","['- 다양한 프레임웍(React, Angular, Vue) 개발 경험', '- A...","['• 점심식사, 간식 지원', '• 4대 보험', '• 자유로운 연차, 반차 사용...","['Git', 'Github', 'Linux', 'MySQL', 'C / C++',...",서울시 서초구 매헌로 8길 47 AI 양재 허브( 희경 재단 B동) 203호
...,...,...,...,...,...,...,...,...,...,...
495,138161,Frontend Developer,포스페이스랩,"['서울', '한국']","['퇴사율5%이하', '설립4~9년', 'IT, 컨텐츠']","['• React 기반의 웹서비스 구축/개발 경험', '• React library...","['• TDD에 대한 이해', '• 브라우저 퍼포먼스에 대한 이해', '• 오픈 소...",['• 주 1회 리모트/사무실 자율 출근 (현재는 금요일 고정)'],"['Github', 'MySQL', 'React', 'HTML', 'JavaScri...",강남구 테헤란로 147
496,149473,Android 보안 솔루션 개발직 A (앱수트팀),스틸리언,"['서울', '한국']","['인원급성장', '51~300명', '설립4~9년', '주35시간', '음료', ...","['[자격 요건]', 'ㆍ안드로이드 개발 경력이 3년 이상이거나 그에 준하는 실력을...","['[우대 사항]', 'ㆍIDE Plugin 개발 경험이 있는 분', 'ㆍProgu...","['* 주 37.5시간 근무 (연구개발 직군의 경우, 주 35시간 근무) (직군별 ...","['Git', 'GitLab', 'JavaScript', 'Python', 'Typ...",서울시 용산구 원효로 90길 11 업무동 12층
497,163705,클라우드 엔지니어 (신입),솔트룩스이노베이션,"['서울', '한국']","['인원급성장', '51~300명', '설립10년이상', '육아휴직', '주차', ...","['• 신입', '• 학력 : 학사이상', '• 남성의 경우 병역 필 또는 면제자로...","['• AWS 관련 자격증 보유자', '• On-premise 운영 관련 경험']","['• 4대보험, 퇴직연금', '• 자기개발 지원 : 자기개발비, 도서구입비 지원'...","['AJAX', 'MySQL', 'Oracle', 'Java', 'JavaScrip...","서울특별시 강남구 언주로 538, 5층(역삼동,대웅빌딩)"
498,153371,프론트 Web 개발자 (2년 이상),아이엠에스모빌리티,"['서울', '한국']","['인원급성장', '50명이하', '설립4~9년', '리프레시휴가', '간식', '...","['• 프론트 개발 경력 2년 이상 혹은 그에 준하는 역량을 보유하신 분', '• ...","['• React Native, Webpack, node.js, AWS 관련 경험']","['• 자율 출/퇴근제 ', ' 08:30 ~ 10:00 사이 자유롭게 출근 후...",NaN,"서울특별시 광진구 아차산로 355, 3층 305호"
499,153932,주니어 프론트엔드 개발자,포자랩스,"['서울', '한국']","['인원급성장', '50명이하', '설립4~9년', '스타트업', '커피', '과일...","['• 프론트엔드 실무 1년 이상 혹은 그에 준하는 경력을 가지신 분', '• Ty...","['• WebAudio API 사용 경험이 있으신 분', '• 웹 사이트 성능 측정...","['• 8~10시 30분 자율 출퇴근 (1일 8시간 근무)', '• 점심 및 커피 ...",NaN,"서울 강남구 테헤란로 78길 16, 노벨빌딩 10층 포자랩스"

In [190]:
position_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5462 entries, 0 to 5461
Data columns (total 36 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       5462 non-null   object
 1   웹 개발자            5462 non-null   int64
 2   서버 개발자           5462 non-null   int64
 3   소프트웨어 엔지니어       5462 non-null   int64
 4   프론트엔드 개발자        5462 non-null   int64
 5   자바 개발자           5462 non-null   int64
 6   C, C++ 개발자       5462 non-null   int64
 7   안드로이드 개발자        5462 non-null   int64
 8   파이썬 개발자          5462 non-null   int64
 9   Node.js 개발자      5462 non-null   int64
 10  iOS 개발자          5462 non-null   int64
 11  머신러닝 엔지니어        5462 non-null   int64
 12  데이터 엔지니어         5462 non-null   int64
 13  시스템, 네트워크 관리자    5462 non-null   int64
 14  DevOps/ 시스템 관리자  5462 non-null   int64
 15  개발 매니저           5462 non-null   int64
 16  기술지원             5462 non-null   int64
 17  QA,테스트 엔지니어      5462 non-null   int64
 18  데이터 사이언티스트       5462 non-null   int64
 19  임베디드 개발자         5462 non-null   int64
 20  보안 엔지니어          5462 non-null   int64
 21  프로덕트 매니저         5462 non-null   int64
 22  빅데이터 엔지니어        5462 non-null   int64
 23  하드웨어 엔지니어        5462 non-null   int64
 24  PHP 개발자          5462 non-null   int64
 25  블록체인 플랫폼 엔지니어    5462 non-null   int64
 26  크로스플랫폼 앱 개발자     5462 non-null   int64
 27  DBA              5462 non-null   int64
 28  ERP전문가           5462 non-null   int64
 29  .NET 개발자         5462 non-null   int64
 30  웹 퍼블리셔           5462 non-null   int64
 31  영상,음성 엔지니어       5462 non-null   int64
 32  그래픽스 엔지니어        5462 non-null   int64
 33  루비온레일즈 개발자       5462 non-null   int64
 34  BI 엔지니어          5462 non-null   int64
 35  VR 엔지니어          5462 non-null   int64
dtypes: int64(35), object(1)
memory usage: 1.5+ MB

In [206]:
position_data = position_data.rename(columns={'Unnamed: 0': 'url'})

for i in range(len(position_data)):
    id = position_data.loc[i, 'url'].split('/')[-1]
    position_data.loc[i, 'id'] = id

tmp_df = position_data[:500]
tmp_df['id'] = tmp_df['id'].astype('int64')

tmp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              500 non-null    object
 1   웹 개발자            500 non-null    int64
 2   서버 개발자           500 non-null    int64
 3   소프트웨어 엔지니어       500 non-null    int64
 4   프론트엔드 개발자        500 non-null    int64
 5   자바 개발자           500 non-null    int64
 6   C, C++ 개발자       500 non-null    int64
 7   안드로이드 개발자        500 non-null    int64
 8   파이썬 개발자          500 non-null    int64
 9   Node.js 개발자      500 non-null    int64
 10  iOS 개발자          500 non-null    int64
 11  머신러닝 엔지니어        500 non-null    int64
 12  데이터 엔지니어         500 non-null    int64
 13  시스템, 네트워크 관리자    500 non-null    int64
 14  DevOps/ 시스템 관리자  500 non-null    int64
 15  개발 매니저           500 non-null    int64
 16  기술지원             500 non-null    int64
 17  QA,테스트 엔지니어      500 non-null    int64
 18  데이터 사이언티스트       500 non-null    int64
 19  임베디드 개발자         500 non-null    int64
 20  보안 엔지니어          500 non-null    int64
 21  프로덕트 매니저         500 non-null    int64
 22  빅데이터 엔지니어        500 non-null    int64
 23  하드웨어 엔지니어        500 non-null    int64
 24  PHP 개발자          500 non-null    int64
 25  블록체인 플랫폼 엔지니어    500 non-null    int64
 26  크로스플랫폼 앱 개발자     500 non-null    int64
 27  DBA              500 non-null    int64
 28  ERP전문가           500 non-null    int64
 29  .NET 개발자         500 non-null    int64
 30  웹 퍼블리셔           500 non-null    int64
 31  영상,음성 엔지니어       500 non-null    int64
 32  그래픽스 엔지니어        500 non-null    int64
 33  루비온레일즈 개발자       500 non-null    int64
 34  BI 엔지니어          500 non-null    int64
 35  VR 엔지니어          500 non-null    int64
 36  id               500 non-null    int64
dtypes: int64(36), object(1)
memory usage: 144.7+ KB

/var/folders/vf/p_2t8d9s3dgc1k68_4bwc6r80000gn/T/ipykernel_16353/62460384.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_df['id'] = tmp_df['id'].astype('int64')

In [203]:
skill_df = job_posting_data[['id', 'title', 'skills']]

print(skill_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      500 non-null    int64
 1   title   500 non-null    object
 2   skills  350 non-null    object
dtypes: int64(1), object(2)
memory usage: 11.8+ KB
None

In [207]:
merge_df = pd.merge(tmp_df, skill_df, on='id')

merge_df

,url,웹 개발자,서버 개발자,소프트웨어 엔지니어,프론트엔드 개발자,자바 개발자,"C, C++ 개발자",안드로이드 개발자,파이썬 개발자,Node.js 개발자,...,.NET 개발자,웹 퍼블리셔,"영상,음성 엔지니어",그래픽스 엔지니어,루비온레일즈 개발자,BI 엔지니어,VR 엔지니어,id,title,skills
0,https://www.wanted.co.kr/wd/82530,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,82530,FLO DBA,"['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaS..."
1,https://www.wanted.co.kr/wd/147597,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,147597,전기차충전기 임베디드 소프트웨어 개발,"['Git', 'Github', 'Linux', 'React', 'SQL', 'AW..."
2,https://www.wanted.co.kr/wd/163951,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,163951,[빗썸] Front End (5년 이상),['Agile']
3,https://www.wanted.co.kr/wd/122553,0,1,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,122553,소프트웨어 엔지니어 (최적화 엔진 개발),"['Git', 'Azure', 'MongoDB', 'Pytorch', 'Scikit..."
4,https://www.wanted.co.kr/wd/157234,0,1,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,157234,SW 개발자 (신입),"['Git', 'Github', 'Linux', 'MySQL', 'C / C++',..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,https://www.wanted.co.kr/wd/138161,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,138161,Frontend Developer,"['Github', 'MySQL', 'React', 'HTML', 'JavaScri..."
496,https://www.wanted.co.kr/wd/149473,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,149473,Android 보안 솔루션 개발직 A (앱수트팀),"['Git', 'GitLab', 'JavaScript', 'Python', 'Typ..."
497,https://www.wanted.co.kr/wd/163705,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,163705,클라우드 엔지니어 (신입),"['AJAX', 'MySQL', 'Oracle', 'Java', 'JavaScrip..."
498,https://www.wanted.co.kr/wd/153371,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,153371,프론트 Web 개발자 (2년 이상),NaN
499,https://www.wanted.co.kr/wd/153932,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,153932,주니어 프론트엔드 개발자,NaN

In [214]:
pre_df = merge_df.drop(['url'], axis=1)
pre_df

,웹 개발자,서버 개발자,소프트웨어 엔지니어,프론트엔드 개발자,자바 개발자,"C, C++ 개발자",안드로이드 개발자,파이썬 개발자,Node.js 개발자,iOS 개발자,...,.NET 개발자,웹 퍼블리셔,"영상,음성 엔지니어",그래픽스 엔지니어,루비온레일즈 개발자,BI 엔지니어,VR 엔지니어,id,title,skills
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,82530,FLO DBA,"['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaS..."
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,147597,전기차충전기 임베디드 소프트웨어 개발,"['Git', 'Github', 'Linux', 'React', 'SQL', 'AW..."
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,163951,[빗썸] Front End (5년 이상),['Agile']
3,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,122553,소프트웨어 엔지니어 (최적화 엔진 개발),"['Git', 'Azure', 'MongoDB', 'Pytorch', 'Scikit..."
4,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,157234,SW 개발자 (신입),"['Git', 'Github', 'Linux', 'MySQL', 'C / C++',..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,138161,Frontend Developer,"['Github', 'MySQL', 'React', 'HTML', 'JavaScri..."
496,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,149473,Android 보안 솔루션 개발직 A (앱수트팀),"['Git', 'GitLab', 'JavaScript', 'Python', 'Typ..."
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,163705,클라우드 엔지니어 (신입),"['AJAX', 'MySQL', 'Oracle', 'Java', 'JavaScrip..."
498,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,153371,프론트 Web 개발자 (2년 이상),NaN
499,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,153932,주니어 프론트엔드 개발자,NaN

In [146]:
job_posting_data.head(3)

,id,title,company,location,tags,qualifications,preferred,benefits,skills,workplace
0,82530,FLO DBA,드림어스컴퍼니,"['서울', '한국']","['인원급성장', '301~1,000명', '설립10년이상', '대출지원', '건강...","['• DBA 경력 5년 이상이신 분', '• 대용량 DBMS 운영 경험하신 분',...","['• 클라우드 환경에서 ISMS 심사 경험이 있는 분', '• 모델링 설계 지원,...","['Work l 드림어스는 개인의 자율성을 존중합니다', '• 선택적 근로시간제에 ...","['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaS...",서초구 강남대로 311 드림플러스 강남 15층
1,147597,전기차충전기 임베디드 소프트웨어 개발,타디스테크놀로지,"['서울', '한국']","['인원급성장', '50명이하', '설립4~9년', '성과급', '스톡옵션', '자...","['• 하드웨어를 제어하는데 관심이 많으신 분', '• 기술 표준 R&D에 관심이 ...","['• 컴퓨터/시스템공학, 전기/전자공학', '• 개발 경험이 있으신 분']","['• 최신형 장비 지원', '- 최신형 맥북이나 델 노트북, 24인치 모니터 지급...","['Git', 'Github', 'Linux', 'React', 'SQL', 'AW...","성동구 성수일로 10 (성수동1가, 서울숲ITCT지식산업센터)"
2,163951,[빗썸] Front End (5년 이상),빗썸코리아,"['서울', '한국']","['연봉상위1%', '인원급성장', '301~1,000명', '설립4~9년', '음...",['• 컴퓨터 공학 또는 관련 분야의 학사 학위 (또는 동등한 실무 경험)를 보유하...,"['• 가상자산 거래소 또는 금융 관련 프로젝트 경험을 보유하신 분', '• 자산 ...","['[업무에 몰입할 수 있는 환경을 조성합니다.]', '', '• 비포괄임금제 | ...",['Agile'],"서울시 강남구 테헤란로 124, 삼원타워 15~17F"

In [127]:
skill_df = job_posting_data[['title', 'skills']]
skill_df.head(10)

                    title                                             skills
0                 FLO DBA  ['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaS...
1    전기차충전기 임베디드 소프트웨어 개발  ['Git', 'Github', 'Linux', 'React', 'SQL', 'AW...
2  [빗썸] Front End (5년 이상)                                          ['Agile']
3  소프트웨어 엔지니어 (최적화 엔진 개발)  ['Git', 'Azure', 'MongoDB', 'Pytorch', 'Scikit...
4             SW 개발자 (신입)  ['Git', 'Github', 'Linux', 'MySQL', 'C / C++',...
5                 백엔드 개발자                                                NaN
6   Front-end 개발자(Junior)                                                NaN
7        [100억↑투자] QA 담당자                                                NaN
8   Data Scientist (3년이상)     ['React', 'JavaScript', 'TypeScript', 'Redux']
9            모바일앱 플러터 개발자  ['JavaScript', 'TypeScript', 'React.js', 'Flut...

In [101]:
skill_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   500 non-null    object
 1   skills  350 non-null    object
dtypes: object(2)
memory usage: 7.9+ KB

In [133]:
skills = skill_df['skills']
skills[0]

tmp_df = pd.DataFrame(skills, columns=['skills'])
tmp_df

                                                skills
0    ['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaS...
1    ['Git', 'Github', 'Linux', 'React', 'SQL', 'AW...
2                                            ['Agile']
3    ['Git', 'Azure', 'MongoDB', 'Pytorch', 'Scikit...
4    ['Git', 'Github', 'Linux', 'MySQL', 'C / C++',...
..                                                 ...
495  ['Github', 'MySQL', 'React', 'HTML', 'JavaScri...
496  ['Git', 'GitLab', 'JavaScript', 'Python', 'Typ...
497  ['AJAX', 'MySQL', 'Oracle', 'Java', 'JavaScrip...
498                                                NaN
499                                                NaN

[500 rows x 1 columns]

In [143]:
skills

0      ['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaS...
1      ['Git', 'Github', 'Linux', 'React', 'SQL', 'AW...
2                                              ['Agile']
3      ['Git', 'Azure', 'MongoDB', 'Pytorch', 'Scikit...
4      ['Git', 'Github', 'Linux', 'MySQL', 'C / C++',...
                             ...
495    ['Github', 'MySQL', 'React', 'HTML', 'JavaScri...
496    ['Git', 'GitLab', 'JavaScript', 'Python', 'Typ...
497    ['AJAX', 'MySQL', 'Oracle', 'Java', 'JavaScrip...
498                                                  NaN
499                                                  NaN
Name: skills, Length: 500, dtype: object

In [115]:
title_skill_rating = job_skills.pivot_table('', index='title', columns='skills')
title_skill_rating

AttributeError: module 'numpy' has no attribute 'rating'

In [142]:
skills = skill_df['skills']
# tmp = 
# tmp_df = pd.DataFrame(tmp, columns=['skills'])
# tmp_df

# 새로운 데이터프레임 생성
new_df = pd.DataFrame({
    'title': skill_df['title'].repeat(skill_df['skills'].str.split(",").len()),
    'skills': ['a', 'b']
})
new_df

AttributeError: 'Series' object has no attribute 'len'

In [103]:
skill_df.T

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
title,FLO DBA,전기차충전기 임베디드 소프트웨어 개발,[빗썸] Front End (5년 이상),소프트웨어 엔지니어 (최적화 엔진 개발),SW 개발자 (신입),백엔드 개발자,Front-end 개발자(Junior),[100억↑투자] QA 담당자,Data Scientist (3년이상),모바일앱 플러터 개발자,...,백엔드 개발자 (Backend Developer),암호화폐 플랫폼 개발,"Backend DevOps 엔지니어 (AWS, Docker, Kubernetes)",파이썬 혹은 node.js 백엔드 서버 개발자,스마트 농업 솔루션 FE 개발자(3년 이상),Frontend Developer,Android 보안 솔루션 개발직 A (앱수트팀),클라우드 엔지니어 (신입),프론트 Web 개발자 (2년 이상),주니어 프론트엔드 개발자
skills,"['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaS...","['Git', 'Github', 'Linux', 'React', 'SQL', 'AW...",['Agile'],"['Git', 'Azure', 'MongoDB', 'Pytorch', 'Scikit...","['Git', 'Github', 'Linux', 'MySQL', 'C / C++',...",NaN,NaN,NaN,"['React', 'JavaScript', 'TypeScript', 'Redux']","['JavaScript', 'TypeScript', 'React.js', 'Flut...",...,NaN,NaN,"['Git', 'Android', 'iOS', 'Java', 'JavaScript'...","['JIRA', 'Django', 'ExpressJS', 'Flask', 'Reac...","['Github', 'React', 'AWS', 'SEO', 'React.js', ...","['Github', 'MySQL', 'React', 'HTML', 'JavaScri...","['Git', 'GitLab', 'JavaScript', 'Python', 'Typ...","['AJAX', 'MySQL', 'Oracle', 'Java', 'JavaScrip...",NaN,NaN

In [17]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder().fit_transform(job_skills['skills'].astype('category'))

ValueError: Expected 2D array, got 1D array instead:
array=["['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaScript', 'TypeScript', 'Figma', 'Next.js', 'Vue.JS']"
 "['Git', 'Github', 'Linux', 'React', 'SQL', 'AWS', 'Docker', 'PostgreSQL', 'Flutter']"
 "['Agile']"
 "['Git', 'Azure', 'MongoDB', 'Pytorch', 'Scikit-Learn', 'Tensorflow', 'Node.js', 'Python', 'C', 'AWS', 'C++', 'Docker', 'Shell Scripting', 'PostgreSQL', 'Golang', 'React.js', 'Next.js', 'Restful API']"
 "['Git', 'Github', 'Linux', 'MySQL', 'C / C++', 'HTML', 'JavaScript', 'Python', 'SQL', 'AWS', 'Spring Framework']"
 nan nan nan "['React', 'JavaScript', 'TypeScript', 'Redux']"
 "['JavaScript', 'TypeScript', 'React.js', 'Flutter', 'Next.js']"
 "['React', 'Java', 'JavaScript', 'PHP', 'SQL']"
 "['Git', 'Android', 'Linux', 'C / C++']"
 "['BitBucket', 'Git', 'JIRA', 'Azure', 'AWS', 'DevOps', 'ITIL', 'Kubernetes']"
 "['Android', 'iOS', 'TypeScript', 'AWS', 'NodeJS', 'React.js']" nan
 "['Linux', 'C', 'C++']" "['React', 'TypeScript']"
 "['Python', 'SQL', 'Tableau', 'AWS', 'Spring Framework', 'ML']"
 "['React', 'TypeScript', 'AWS', 'Restful API', 'Vue.JS']" nan
 "['Python', 'SQL', 'SCM']"
 "['Git', 'Github', 'MySQL', 'AWS', 'Spring Framework']"
 "['React', 'TypeScript']"
 "['Git', 'JIRA', 'Pytorch', 'C++', 'CUDA', 'OpenCV', 'OpenMP', 'ML']"
 "['Django', 'Python']"
 "['React', 'CSS', 'HTML', 'JavaScript', 'TypeScript']"
 "['Git', 'Github', 'Android', 'Azure', 'iOS', 'Linux', 'MySQL', 'React', 'C / C++', 'HTML', 'Java', 'JavaScript', 'Kotlin', 'Node.js', 'ObjectiveC', 'PHP', 'Python', 'SQL', 'Swift', 'AWS', 'C++', 'REST', 'ISO', 'Docker', 'Shell Scripting', 'Spring Framework', 'JPA', 'Flutter', 'Kubernetes']"
 "['Hyperledger', 'Java', 'JavaScript', 'Kotlin', 'Node.js', 'Go', 'Docker', 'Spring Framework', 'React.js', 'React Native', 'Flutter', 'Kubernetes', 'Vue.JS']"
 nan "['AWS', 'ElasticSearch']" "['MySQL', 'JavaScript', 'PHP']"
 "['Github', 'Linux', 'C / C++', 'Python', 'ROS']" nan nan nan
 "['Git', 'Github', 'Android', 'Azure', 'iOS', 'Linux', 'MySQL', 'React', 'C / C++', 'HTML', 'Java', 'JavaScript', 'Kotlin', 'Node.js', 'ObjectiveC', 'PHP', 'Python', 'SQL', 'Swift', 'AWS', 'C++', 'REST', 'ISO', 'Docker', 'Shell Scripting', 'Spring Framework', 'JPA', 'Flutter', 'Kubernetes']"
 nan "['Git', 'MySQL', 'Java', 'JavaScript', 'React.js', 'Spring Boot']"
 "['Github', 'Linux', 'Pytorch', 'Tensorflow', 'Python', 'Docker', 'PostgreSQL', 'RHEL', 'Ubuntu', 'OpenCV', 'FastAPI']"
 "['React', 'JavaScript', 'JSP', 'NodeJS', 'Vue.JS']"
 "['Hadoop', 'Scikit-Learn', 'Spark', 'Tensorflow', 'Python', 'SQL', 'Tableau', 'Go']"
 "['Git', 'Android', 'iOS', 'MySQL', 'VueJS', 'HTML', 'Java', 'JavaScript', 'AWS', 'jQuery', 'Bootstrap', 'JSP', 'Spring Framework', 'Axure', 'Figma']"
 nan
 "['Git', 'Github', 'Android', 'Azure', 'iOS', 'Linux', 'MySQL', 'React', 'C / C++', 'HTML', 'Java', 'JavaScript', 'Kotlin', 'Node.js', 'ObjectiveC', 'PHP', 'Python', 'SQL', 'Swift', 'AWS', 'C++', 'REST', 'ISO', 'Docker', 'Shell Scripting', 'Spring Framework', 'JPA', 'Flutter', 'Kubernetes']"
 "['Git', 'Firebase', 'C#', 'Python', 'AWS', 'Flutter']"
 "['Hadoop', 'Linux', 'React', 'C / C++', 'JavaScript', 'Python', 'SQL', 'C++', 'Docker', 'Spring Framework', 'MSSQL', 'Kubernetes']"
 nan nan "['C / C++', 'HTML', 'JavaScript', 'Python']"
 "['Java', 'API', 'Spring Boot']"
 "['Git', 'React', 'JavaScript', 'Node.js', 'Visual Studio', 'Spring Boot', 'Vue.JS']"
 "['SAP', 'SAP ERP', 'SAP 구현', 'SAP SD', 'SAP MM', 'SAP FICO', 'SAP FI', 'SAP HR']"
 "['Zeplin', 'Confluence', 'Git', 'Github', 'JIRA', 'Slack', 'React', 'React Native', 'Figma', 'Notion']"
 "['Linux', 'HTML', 'JavaScript', 'PHP', 'SQL']"
 "['Node.js', 'TypeScript', 'AWS']"
 "['Linux', 'C / C++', 'Python', 'C++', '인터페이스', '펌웨어', 'WPF', 'RTOS', 'Embedded Linux', 'Qt', 'MFC']"
 "['Git', 'Github', 'React', 'VueJS', 'Java', 'AWS', 'Docker', 'Spring Framework', 'JPA', 'Spring Boot']"
 "['Github']" nan nan
 "['Azure', 'Pytorch', 'Python', 'AWS', 'DevOps', 'ML']"
 "['Spring Framework']" nan
 "['MongoDB', 'Python', '금융', 'API', 'NoSQL', 'ElasticSearch', 'API 개발']"
 "['React']"
 "['Git', 'JavaScript', 'PostgreSQL', 'Kubernetes', 'Nest.js', 'Vue.JS']"
 "['Android', 'Java', 'Kotlin', '안드로이드 개발', 'Flutter']" nan
 "['Git', 'Github', 'React', 'JavaScript', 'Python', 'AWS', 'Docker', 'PostgreSQL', 'Spring Framework', 'JPA']"
 "['Github', 'Pytorch', 'Spark', 'Python', 'AWS', 'Docker', 'Kubernetes']"
 "['Java', 'Kotlin', 'Scala', 'AWS', 'Spring Boot', 'Kubernetes']" nan
 "['Java', 'JavaScript', 'jQuery', 'RDBMS', 'Spring Framework']"
 "['Android', 'JavaScript', 'TypeScript', 'React.js', 'Redux', 'Next.js']"
 "['Android', 'Django', 'iOS', 'React', 'Node.js', 'Laravel', 'React Native', 'Spring Boot', 'Flutter', 'Nest.js']"
 "['MongoDB', 'Redis', 'JavaScript', 'Node.js', 'React.js', 'ES6', 'Next.js']"
 nan "['Django', 'React', 'AWS', 'React Native']"
 "['Git', 'Android', 'Linux', 'React', 'C / C++', 'HTML', 'Java', '펌웨어']"
 "['Git', 'Android', 'iOS', 'Java', 'JavaScript', 'Node.js', 'Python', 'OOP', 'AWS', 'SaaS']"
 nan "['Linux', 'Oracle', 'Java', 'JSP', 'Spring Boot']"
 "['Git', 'MySQL', 'Python', '개발', 'AWS', '솔루션 개발']"
 "['Git', 'Github', 'Linux', 'MongoDB', 'MySQL', 'React', 'HTML', 'JavaScript', 'AWS', 'Docker']"
 "['Git', 'ExpressJS', 'React', 'CSS', 'HTML', 'JavaScript', 'TypeScript', 'AWS', 'NodeJS']"
 "['Git', 'VueJS', 'JavaScript', 'Node.js', 'TypeScript', 'AWS', 'React.js']"
 "['Zeplin', 'Android', 'Ethereum', 'iOS', 'CSS', 'HTML', 'Java', 'JavaScript', 'Kotlin', 'Node.js', 'PHP', 'Swift', 'MVC', 'MVVM', 'API', 'NodeJS', 'Spring Framework', 'API 개발', 'Laravel', 'CakePHP', 'Figma']"
 nan "['JavaScript', 'HTML5', 'CSS 자바 스크립트']" nan
 "['Git', 'Linux', 'MySQL', 'JavaScript', 'SQL', 'TypeScript', 'AWS', 'Nest.js']"
 "['Flask', 'Pytorch', 'Tensorflow', 'Python', 'Data Analysis', 'API 개발', 'FastAPI', 'ML']"
 "['Github', 'WebGL', 'Node.js', 'AWS', 'C++', 'Docker', 'ElasticSearch', 'Google Apps', 'Qt', 'React.js', 'Notion', 'Next.js', 'Nest.js']"
 "['Git', 'MySQL', 'React', 'Node.js', 'TypeScript', 'PostgreSQL', 'ORM']"
 nan
 "['React', 'VueJS', 'CSS', 'JavaScript', 'HTML5', 'JPA', 'JSTL', 'React.js']"
 nan "['React', 'JavaScript', 'JSP', 'NodeJS', 'Vue.JS']"
 "['Git', 'Github', 'Android', 'Azure', 'iOS', 'Linux', 'MySQL', 'React', 'C / C++', 'HTML', 'Java', 'JavaScript', 'Kotlin', 'Node.js', 'ObjectiveC', 'PHP', 'Python', 'SQL', 'Swift', 'AWS', 'C++', 'REST', 'ISO', 'Docker', 'Shell Scripting', 'Spring Framework', 'JPA', 'Flutter', 'Kubernetes']"
 "['.NET', 'C#', 'CSS', 'HTML', 'JavaScript', 'MVC', 'MSSQL']"
 "['PHP', 'MSSQL', 'Restful API']" nan nan
 "['React', 'JavaScript', 'TypeScript', 'Redux']"
 "['Git', 'Github', 'GraphQL', 'Python', 'AWS', 'PostgreSQL']"
 "['Android', 'MySQL', 'C#', 'Java', 'Node.js', 'PHP', 'Go', 'C++', 'API', '서버 아키텍처', 'iOS 개발', '프론트엔드 개발자', '백엔드 개발']"
 "['Git', 'TypeScript', 'React Native']"
 "['Git', 'Linux', 'Pytorch', 'Python', 'SQL', 'AWS']"
 "['Git', 'C++', 'API']"
 "['Github', 'WebGL', 'Node.js', 'AWS', 'C++', 'Docker', 'ElasticSearch', 'Google Apps', 'Qt', 'React.js', 'Notion', 'Next.js', 'Nest.js']"
 nan nan
 "['Git', 'ExpressJS', 'Linux', 'MySQL', 'JavaScript', 'NodeJS', 'CentOS', 'ORM', 'Ubuntu']"
 "['Android', 'iOS', 'MySQL', 'Oracle', 'Java', 'JSP', 'Spring Boot']" nan
 nan nan
 "['JavaScript', 'TypeScript', 'React.js', 'React Native', 'Next.js']"
 "['Django', 'MySQL', 'Python', 'AWS', 'Docker']"
 "['Azure', 'ASP .NET', 'C#', 'Java', 'Python']" "['Git']"
 "['Git', 'Linux', 'MongoDB', 'MySQL', 'React', 'Redis', 'C / C++', 'CSS', 'HTML', 'Java', 'JavaScript', 'PHP', 'SQL', 'API', 'Docker', '컴퓨터 공학', 'CSS3', 'CSS 자바 스크립트', 'Spring Framework', 'Restful API']"
 nan
 "['Android', 'iOS', 'Java', 'JavaScript', 'Kotlin', 'Python', 'Swift', 'PostgreSQL', 'Spring Framework']"
 "['Git', '.NET', 'React', 'ASP', 'C#', 'HTML', 'Java', 'JavaScript', 'AWS', 'jQuery', 'HTML5', 'NoSQL', 'Docker', 'DART for Publishers', 'Flutter']"
 "['Github', 'Android', 'Firebase', 'iOS', 'MySQL', 'Java', 'JavaScript', 'PHP', 'Python', 'AWS']"
 "['HCI', 'Linux', '인프라', 'VM웨어', 'Active Directory', 'Windows 서버', '시스템 관리', 'VDI', '시스템 구축', 'VMware Infrastructure', 'Windows 원격 데스크톱']"
 nan
 "['Git', 'Android', 'iOS', 'MySQL', 'JavaScript', 'Kotlin', 'Node.js', 'PHP', 'Swift', 'AWS', 'Product Management ', 'Spring Framework', 'QA 엔지니어링']"
 nan nan "['SQL', 'AWS', 'POS', 'RFP', '네트워크 설계']"
 "['Java', 'AWS', 'Spring Boot']" "['VueJS', 'TypeScript']"
 "['Git', 'Github', 'GraphQL', 'React', 'JavaScript', 'Node.js', 'TypeScript', 'HTML5', 'RESTful WebServices', 'React Native', 'ES6']"
 nan
 "['Linux', 'C / C++', 'Perl', 'Python', 'FPGA', 'SoC', 'Verilog', 'Embedded Linux', 'EDA', 'FPGA 프로토 타이핑']"
 "['Git', 'HTML', 'JavaScript', '소프트웨어 개발', '웹 개발', '수학', '컴퓨터 비전', '의료 영상', '프론트엔드 개발자']"
 "['SAP', 'AWS', 'SAP ERP']" nan
 "['Git', 'Linux', 'C / C++', 'Java', 'SQL', 'UNIX', 'Docker']" nan
 "['Amazon Web Service', 'Linux', '인프라', 'AWS', '서버', 'DNS', 'Windows 서버', 'Apache', 'DHCP', '시스템 관리', 'CentOS', '서버 관리', 'Ubuntu', 'Nginx', '서버 관리', 'LIS', '시스템 구축']"
 "['Git', 'Github', 'JIRA', 'Slack', 'Java', 'AWS', 'Spring Framework', 'ORM', 'Notion']"
 "['Github', 'Linux', 'HTML', 'Java', 'JavaScript', 'SQL', 'Spring Framework']"
 "['iOS', 'Swift', 'Restful API']" nan
 "['Github', 'Azure', 'Linux', 'MySQL', 'C / C++', 'JSON', 'MSSQL']"
 "['MySQL', 'Java', 'JavaScript', 'Node.js', 'AWS', 'Spring Framework']"
 "['Github', 'Pytorch', 'React', 'Tensorflow', 'C / C++', 'Python', 'Docker', 'Golang']"
 "['C / C++']" nan "['SQL']"
 "['Git', 'Github', 'Unreal Engine', 'C#', 'Python', 'C++', 'CAN', 'ROS', 'Unity3D']"
 "['Git', 'Github', 'iOS', 'Linux', 'MySQL', 'HTML', 'JavaScript', 'Swift', 'AWS', 'Spring Framework']"
 nan "['인공 지능', '컴파일러']" nan nan
 "['Oracle', 'React', 'ASP .NET', 'C#', 'CSS', 'HTML', 'Java', 'JavaScript', 'SQL', 'C', 'C++', 'EMR', 'Bootstrap', 'WPF', 'PACS', 'MFC']"
 "['Android', 'iOS', 'Java', 'Kotlin', 'PHP', 'Flutter']"
 "['TypeScript', 'React.js', 'Next.js']"
 "['Azure', 'Pytorch', 'Python', 'AWS', 'DevOps', 'ML']"
 "['Git', 'iOS', 'HTML', 'Node.js', 'Python', 'AWS', 'React Native']"
 "['C++']"
 "['Android', 'Azure', 'iOS', 'MySQL', 'ASP .NET', 'C / C++', 'C#', 'JavaScript', 'MVC', 'AWS', 'API', 'Golang', 'MSSQL', 'Restful API']"
 nan nan "['Pytorch', 'Tensorflow', 'Python', 'Docker', 'Kubernetes']"
 "['Git', 'AJAX', 'Android', 'MySQL', 'Tensorflow', 'Java', 'JavaScript', 'Kotlin', 'Python', 'SQL', 'Swift', 'AWS', 'C++', 'NoSQL', 'Spring Framework', 'JPA']"
 "['Java', 'JavaScript', 'Spring Framework', 'Spring Boot']" "['iOS']" nan
 nan nan nan nan nan
 "['Java', 'JavaScript', 'AWS', 'TCP', 'C++', 'UDP', 'GCP', 'Unity3D', 'React.js']"
 "['Android', '.NET', 'iOS', 'Linux', 'MySQL', 'Spark', 'C / C++', 'HTML', 'Java', 'ObjectiveC', 'Python', 'SQL', 'Swift', 'Agile', 'AWS', 'C++', 'VM웨어', 'DevOps', 'Jenkins', 'Mac', 'PMP', 'Citrix', 'CISA', 'OpenStack', 'Xamarin', 'Xen', '영어 실력', 'OSS', 'Kubernetes']"
 nan nan "['AWS', 'Kubernetes']"
 "['Github', 'AngularJS', 'MongoDB', 'JavaScript', 'Python', 'TypeScript', 'AWS', 'CSS3', 'Spring Framework', 'GCP', 'Spring Boot']"
 "['Git', 'MySQL', 'React', 'JavaScript', 'TypeScript', 'AWS', 'Jenkins', 'Docker', 'Spring Framework', 'React Native']"
 "['Linux', 'C / C++', 'Perl', 'Python', 'FPGA', 'SoC', 'Verilog', 'Embedded Linux', 'EDA', 'FPGA 프로토 타이핑']"
 nan nan
 "['Git', 'Android', 'Firebase', 'iOS', 'Linux', 'React', 'Java', 'Kotlin', 'Swift', 'TypeScript', 'Google Analytics', 'AWS', '데이터베이스', 'Windows 서버', 'Docker', '네트워크 운영', 'Spring Framework', 'Xcode', 'iOS 개발', 'Android Studio', 'React.js', 'Spring Boot', 'Google Tag Manager']"
 "['C#', 'Delphi', 'Kotlin', 'C', 'MFC']" nan
 "['React', 'Node.js', 'Python', 'AWS', 'Docker', 'API 개발', 'Flutter', 'ML']"
 "['Java', 'AWS', 'VM웨어', '가상화', 'Tomcat', 'Nginx', 'RAID']" "['C++']"
 "['Azure', 'AWS', 'Kubernetes']" "['AWS', 'DevOps', 'Docker', 'GCP']"
 "['Git', 'Slack', 'MySQL', 'Redis', 'HTML', 'Java', 'JavaScript', 'AWS', 'jQuery', 'Docker', 'PostgreSQL', 'JPA', 'OAuth', 'Spring Boot', 'Notion', 'Kubernetes']"
 "['Github', 'React', 'CSS', 'HTML', 'JavaScript', 'TypeScript', 'AWS']"
 "['Pytorch', 'Python', 'NumPy']"
 "['Git', 'MATLAB', 'Linux', 'C / C++', 'Python']"
 "['Github', 'JavaScript', 'TypeScript', 'AWS', 'NodeJS', 'Nest.js']" nan
 "['Git', 'Android', 'Linux', 'C / C++']" nan nan
 "['Git', 'SQL', 'AWS', 'NoSQL', 'Spring Framework']" "['Oracle', 'Java']"
 "['Framer', 'CSS', 'HTML', 'Figma', 'Next.js']"
 "['Confluence', 'Git', 'Github', 'JIRA', 'SQL', 'CRM', 'API', 'GCP', 'ERP 소프트웨어']"
 "['Linux', 'C / C++', 'Java', 'Perl', 'Python', 'Shell', '딥 러닝', 'DevOps', 'Jenkins', 'Bash', 'FPGA', 'SoC', 'Verilog', 'VHDL', 'RTL 설계', 'RTL 코딩', 'RTL 검증']"
 "['Git', 'Android', 'iOS', 'MySQL', 'Pytorch', 'React', 'Tensorflow', 'Java', 'JavaScript', 'Kotlin', 'Python', 'Swift', '딥 러닝', 'AWS', '신호 처리', '인공 지능', 'JPA', 'Spring Boot', 'ML']"
 "['Zeplin', 'Git', 'JIRA', 'Slack', 'MySQL', 'React', 'TypeScript', 'AWS', 'React.js', 'React Native', 'Figma', 'Notion', 'Nest.js']"
 "['MySQL', 'Java', 'NoSQL', 'RESTful WebServices', 'Spring Boot']"
 "['Git', 'Azure', 'MongoDB', 'Pytorch', 'Scikit-Learn', 'Tensorflow', 'Node.js', 'Python', 'C', 'AWS', 'C++', 'Docker', 'Shell Scripting', 'PostgreSQL', 'Golang', 'React.js', 'Next.js', 'Restful API']"
 "['Linux', 'C++', 'Visual Studio', 'MSSQL']"
 "['BitBucket', 'Confluence', 'Git', 'JIRA', 'Linux', 'Pytorch', 'Scikit-Learn', 'Tensorflow', 'C#', 'Python', 'GPU', 'CUDA', 'NumPy', 'SciPy']"
 "['Azure', 'Hadoop', 'MongoDB', 'MySQL', 'VueJS', 'CSS', 'Java', 'Python', 'Scala', 'SQL', 'Power BI', 'Tableau', 'AWS', 'NoSQL', 'GCP', 'Apache Spark', 'Apache Kafka']"
 nan nan
 "['Git', 'Android', 'ExpressJS', 'iOS', 'Linux', 'React', 'Ruby on Rails', 'VueJS', 'CSS', 'Java', 'JavaScript', 'AWS', 'jQuery', 'Docker', 'PostgreSQL', 'NodeJS', 'Flutter']"
 nan
 "['Git', 'Linux', 'Redis', 'Java', 'Jenkins', 'API 개발', '백엔드 개발', 'ANSI C', 'Spring Boot']"
 "['Git', 'Android', 'ExpressJS', 'iOS', 'Linux', 'React', 'Ruby on Rails', 'VueJS', 'CSS', 'Java', 'JavaScript', 'AWS', 'jQuery', 'Docker', 'PostgreSQL', 'NodeJS', 'Flutter']"
 nan
 "['MongoDB', 'React', 'JavaScript', 'Python', 'TypeScript', 'AWS', 'Nest.js']"
 "['Android', 'Firebase', 'Kotlin', 'Android Studio', 'Mixpanel']" nan
 "['Git', 'Github', 'MySQL', 'React', 'CSS', 'HTML', 'JavaScript', 'Node.js', 'TypeScript', 'AWS', 'Docker', 'React.js', 'React Native', 'Next.js']"
 "['MySQL', 'Node.js', 'PHP', 'CodeIgniter', 'Vue.JS']"
 "['Java', 'JavaScript', 'Python', 'TypeScript', 'AWS', 'Go', 'C++', 'Spring Framework']"
 "['AngularJS', 'React', 'VueJS', 'CSS', 'JavaScript', 'TypeScript', 'HTML5', 'Next.js']"
 "['Android', 'Kotlin', 'AWS', '펌웨어']"
 "['BitBucket', 'Git', 'JIRA', 'Slack', 'MySQL', 'React', 'Redis', 'Google Analytics', 'AWS', 'Go', 'Docker', 'React Native', 'Figma', 'Notion']"
 "['Github', 'React']" nan "['MySQL', 'Oracle', 'MSSQL']"
 "['Java', 'JavaScript']"
 "['Confluence', 'GitLab', 'JIRA', 'Linux', 'SQL', '인프라', 'AWS', 'DevOps', 'ITIL', 'Docker', '시스템 관리', 'VPN', '네트워크 운영', 'IT 운영', 'IT 관리']"
 nan
 "['Git', 'Android', 'iOS', 'Java', 'JavaScript', 'Node.js', 'Python', 'OOP', 'AWS', 'SaaS']"
 nan
 "['Git', 'ExpressJS', 'GraphQL', 'JavaScript', 'Node.js', 'TypeScript', 'AWS', 'Jenkins', 'NoSQL', 'Docker', 'RDBMS', 'EC2', 'NodeJS', 'Next.js']"
 "['Confluence', 'Git', 'JIRA', 'AWS']" nan nan nan nan
 "['Java', 'Kotlin', 'Scala', 'AWS', 'Spring Boot', 'Kubernetes']" nan
 "['Git', 'ExpressJS', 'React', 'CSS', 'HTML', 'JavaScript', 'TypeScript', 'AWS', 'NodeJS']"
 nan nan "['Android', 'iOS', 'TypeScript', 'AWS', 'Flutter']" nan nan nan
 nan "['VueJS', 'CSS', 'HTML', 'JavaScript', 'React.js']"
 "['Git', 'Android', 'ExpressJS', 'iOS', 'TypeScript', 'Scrum', 'Agile', 'AWS', 'NodeJS', 'Android Studio', 'IntelliJ IDEA', 'Visual Studio Code', 'Flutter', 'Notion']"
 "['Linux', 'Java', 'Python', 'C++', '검증', 'SoC', 'ASIC', 'RTL 설계']"
 "['React', 'HTML', 'JavaScript']"
 "['Git', 'JIRA', 'React', 'CSS', 'HTML', 'JavaScript', 'TypeScript', 'Figma', 'Next.js', 'Vue.JS']"
 "['Python', '보안', '인프라', 'AWS']" "['Android', 'iOS', 'UX']" nan
 "['Linux', 'C / C++', 'Python', 'SQL', 'AWS', 'Docker']"
 "['Android', 'Linux', 'C / C++', '개발', '연구 및 개발', '기술 개발']" nan
 "['Github', 'Android', 'iOS', 'AWS', 'Go', 'RESTful WebServices', 'React.js', 'Next.js']"
 "['Git', 'iOS', 'React', 'C / C++', 'JavaScript', 'Python', 'AWS']" nan
 nan
 "['Git', 'Github', 'MongoDB', 'MySQL', 'Pytorch', 'Scikit-Learn', 'JavaScript', 'Node.js', 'R', 'SQL', 'AWS', 'Jenkins', 'NoSQL', 'Apache', 'Docker', 'JUnit', 'MSSQL', 'Kubernetes']"
 "['Git', 'Android', 'iOS', 'MySQL', 'C / C++', 'HTML', 'JavaScript', 'Kotlin', 'Python', 'SQL', 'Swift', 'AWS', 'Docker', 'Spring Framework']"
 "['CSS', 'HTML', 'JavaScript', 'Blockchain']" nan
 "['Github', 'AngularJS', 'React', 'JavaScript', 'Flutter', 'Next.js']"
 "['Git', 'Linux', 'MySQL', 'C / C++', 'HTML', 'Java', 'Python', 'AWS', 'Docker', 'CSS3', 'Nginx', 'Spring Boot']"
 "['Git', 'Github', 'React', 'JavaScript', 'AWS']" "['JIRA', 'Notion']"
 "['Azure', 'Linux', 'AWS', 'Cisco', 'DNS', 'Docker', 'PaaS', 'GCP', 'Kubernetes']"
 "['Confluence', 'JIRA', 'Slack', 'AWS', 'Gradle', 'Spring Boot']"
 "['Git', 'C++', 'API']" "['Java', 'WebSphere MQ']" nan
 "['Git', 'Linux', 'MySQL', 'JavaScript', 'SQL', 'TypeScript', 'AWS', 'Nest.js']"
 nan
 "['Github', 'Pytorch', 'React', 'Tensorflow', 'C / C++', 'Python', 'Docker', 'Golang']"
 "['CSS', 'HTML', 'JavaScript', 'TypeScript', 'React.js', 'React Native', 'Next.js', 'Vue.JS']"
 "['Spring Framework']"
 "['Git', 'Android', 'MySQL', 'ASP', 'C#', 'HTML', 'Java', 'JavaScript', 'Node.js', 'Python', 'Visual Basic', 'jQuery', 'PowerBuilder', 'MSSQL']"
 nan nan nan nan
 "['.NET', 'C#', '하드웨어', 'C++', '전자 공학', '통신', '로봇', '펌웨어', '회로', '하드웨어 설계', '회로 설계', '모터 제어', '전력전자학', '인버터', '시스템 구축', '로봇 프로그래밍', '제어 시스템 설계']"
 "['GraphQL', 'React', 'CSS', 'HTML', 'Java', 'JavaScript', 'TypeScript', 'NoSQL', 'RDBMS', 'ElasticSearch', 'NodeJS', 'Figma', 'Restful API']"
 "['서비스 디자인', 'Android', 'iOS', 'React', 'JavaScript', 'Python', '브랜딩', 'AWS', 'NoSQL', 'Docker', '그래픽 디자인', 'Adobe Photoshop', 'Spring Framework', 'Adobe Illustrator', 'UI 디자인', 'Figma']"
 nan nan
 "['Git', 'JavaScript', 'Shell', 'Jenkins', 'Docker', 'NodeJS', 'Kubernetes']"
 "['Oracle', 'Java', 'JavaScript', 'jQuery', 'Spring Framework']"
 "['Git', 'MongoDB', 'MySQL', 'Oracle', 'React', 'Redis', 'PHP', 'OOP', 'AWS', 'Docker', 'PostgreSQL', 'Laravel', 'React.js', 'Spring Boot']"
 nan nan "['React', 'CSS', 'HTML', 'JavaScript', 'TypeScript']"
 "['C#', 'Python', 'SQL', 'Power BI', 'Tableau', 'SQL 서버', 'SSIS', 'OLAP', 'MDX']"
 "['React', 'CSS', 'HTML', 'JavaScript', 'TypeScript', '개발', 'Docker', '검색 엔진', 'React Native']"
 "['Linux', 'Python', 'AWS', 'Docker', 'Bash', 'NodeJS', 'Kubernetes']"
 "['CISSP', 'CISA']" "['Node.js', 'Unity3D']" nan
 "['Github', 'Pytorch', 'Spark', 'Python', 'AWS', 'Docker', 'Kubernetes']"
 "['Kubernetes']"
 "['Git', 'Github', 'Django', 'MySQL', 'JavaScript', 'Python', 'TypeScript', 'AWS', 'React.js']"
 "['Git', 'MySQL', 'C / C++', 'Python', 'AWS', 'NoSQL', 'RDBMS', 'GCP']"
 "['MySQL', 'JavaScript', 'PHP', 'jQuery', 'Jenkins', 'SVN']" nan
 "['Git', 'Django', 'Pytorch', 'Tensorflow', 'C / C++', 'Python', 'Docker', 'FastAPI']"
 "['Git', 'Slack', 'Linux', 'Pytorch', 'Tensorflow', 'Python', 'SQL', 'Docker', 'OpenCV']"
 nan nan nan nan
 "['Git', 'Github', 'Android', 'Azure', 'iOS', 'Linux', 'MySQL', 'React', 'C / C++', 'HTML', 'Java', 'JavaScript', 'Kotlin', 'Node.js', 'ObjectiveC', 'PHP', 'Python', 'SQL', 'Swift', 'AWS', 'C++', 'REST', 'ISO', 'Docker', 'Shell Scripting', 'Spring Framework', 'JPA', 'Flutter', 'Kubernetes']"
 "['C#', 'Python', 'C']" nan nan nan nan
 "['React', 'HTML', 'JavaScript', 'SQL']" "['MySQL', 'Spring Framework']"
 "['React', 'JavaScript', 'TypeScript', 'Redux']" nan
 "['Git', 'MATLAB', 'JavaScript', 'Python', 'TypeScript', 'C', 'C++', 'UI 디자인', 'React.js']"

In [7]:
title_skill_rating = job_posting_data.pivot_table('rating', index='title', columns='skills')

KeyError: 'rating'